### ISSUE TITLE
Custom hotkeys

### ISSUE THREAD

**Issue by 2099492** [glsorre/amethystwindows#12]
I would realy like to customize my hotkeys like I can do with the mac version of this program. I don't know if it is already in there I couldn't, find maybe I am just stupid idk.

**Comment by glsorre** [comment]
Hi Thank you for your request. It will come. I am developing the app in my free time but it will come.

**Comment by glsorre** [comment]
Hello @2099492. This feature is implemented in #19. Please track it.
