### ISSUE TITLE
Add mouse-drag to resize and reorder windows

### ISSUE THREAD

**Issue by snaphat** [glsorre/amethystwindows#15]
Two question/requests:

1) Would it be possible to add the ability to use the mouse to resize the windows similar to aero-snap? 

2) Would it be possible to add the ability to reorder windows by dragging one window over the area of another window (causing them to swap positions)?

What I'm interested in wrt this project is having mouse controls added for window manipulation. I've half thought about attempting to add these myself, but I wasn't really sure how much control UWP gives you or whether it would be a giant hassle to setup the environment.

**Comment by snaphat** [comment]
Window reordering via mouse support:
https://github.com/glsorre/amethystwindows/compare/master...snaphat:master

**Comment by glsorre** [comment]
Hello @snaphat will give a look to your proposal during the weekend. In the meanwhile thanks.

**Comment by glsorre** [comment]
Hello @snaphat ! First of all sorry for so late reply. I am gonna retake the project into active development and I do not want to refuse your proposal.

I have given a look to your PR and here is my main observation: the solution is a bit simplistic as is assumes the layout is composed from 2 windows only.

If you could abstract more and make it work for multiple windows layouts (n > 2) I would be happy to merge as direct manipulation of windows is something I would like to achieve.
