### ISSUE TITLE
Setting for the default width of the Master Pane

### ISSUE THREAD

**Issue by domsch1988** [glsorre/amethystwindows#16]
By default, the Master Pane takes up 50% of the screen. I have to set the through the hotkeys every time i restart Amethyst and for every Dektop seperately.
It would be nice if the last setting got saved on closing amethyst and if there would be a setting for the default width.

**Comment by glsorre** [comment]
Hello @domsch1988. Sorry for late reply. It is my intention to implemets this into #19. Keep track of it.
