### ISSUE TITLE
App Installer failed to install package dependencies. Ask the developer for  package. 

### ISSUE THREAD

**Issue by roytseng-tw** [glsorre/amethystwindows#17]
**Describe the bug**
I failed to install the app on windows 10 version 1709.

**To Reproduce**
1. double click the appxbundle file.
2. wait and see the error.

**Comment by glsorre** [comment]
Can you try to install it trough this? https://www.microsoft.com/it-it/p/programma-di-installazione-app/9nblggh4nns1?activetab=pivot:overviewtab

Give it a try and let me know.

**Comment by roytseng-tw** [comment]
Hi, I did install through the app installer.

**Comment by glsorre** [comment]
Can you try to update windows? I think version 1709 is not supported.

**Comment by cybardev** [comment]
#### My installation fails with this error: Class not registered (0x80040154)
#### I tried both the `Install` button on the website, and by downloading the `appxbundle` file. Both show the same error.
```
Windows Build: 19043.1021
```
#### Any solutions?

![image](https://user-images.githubusercontent.com/50134239/127409906-ab648ffa-1183-4752-a800-2142fa47ce82.png)

**Comment by midoBB** [comment]
Seconding the error above
![image](https://user-images.githubusercontent.com/1252393/143599753-3d187e22-7059-4d11-bd52-a64f22b3c597.png)

**Comment by glsorre** [comment]
Please update windows and retry. :)
