### ISSUE TITLE
Spacing between two windows should equal the value of the set padding.

### ISSUE THREAD

**Issue by KHNRV** [glsorre/amethystwindows#21]
**Is your feature request related to a problem? Please describe.**
As I understand, when setting padding of 10px in the settings, for example. The spacing between my windows and the border of my screen is going to be 10px. Although, the spacing in between windows is going to be 20px.

**Describe the solution you'd like**
I believe the spacing between two windows should be equal to the set padding. For this example, it would be 10px or the equivalent of the sum of two paddings divided by two.

Making a hypothesis on how the app works, I wonder if it would be possible to apply the padding settings to the border of the desktop space itself. I believe this would make things more consistent without too much code alteration. But maybe I'm wrong.

![image](https://user-images.githubusercontent.com/29149595/117546731-d6c6c380-aff9-11eb-86ef-b57e5f1be089.png)

**Note**
This is a fantastic project. I am a big Regolith user on Linux, and your project Is by far the closest thing I found for Windows. I am no C# developer (yet?), but I would love to give you a hand.

**Comment by glsorre** [comment]
@KHNRV you are probably right. At the moment the padding is applied at application level so every application has on all sides the padding specified. I will address it.

**Comment by glsorre** [comment]
Screen margin are going to be implemented with #22.
Window padding is going to stay.
Layout Padding is a bit more complicated, going to implement it in the future.

I won't close this issue to keep track.

**Comment by glsorre** [comment]
Hello @KHNRV this has been released. Check https://github.com/glsorre/amethystwindows/releases/tag/1.0.21132.1

**Comment by glsorre** [comment]
Hello @KHNRV. Layut padding is implemented in #25.

**Comment by glsorre** [comment]
Hello, this has been released: https://github.com/glsorre/amethystwindows/releases/tag/1.0.21135.2
