### ISSUE TITLE
remove window decoration

### ISSUE THREAD

**Issue by eskoONE** [glsorre/amethystwindows#31]
**Is your feature request related to a problem? Please describe.**
would be nice if one could disable to top window decoration where you can minimize/maximize/close.

**Describe the solution you'd like**
hiding the window decorator and manage the windows through hotkeys, to move, resize, close, etc.

**Describe alternatives you've considered**
alternative would be to not bother with this feature request, as it might break more things in windows than necessary.

**Additional context**
[bugn](https://github.com/fuhsjr00/bug.n), another window manager for windows, has such a feature. might want to look at how its done in there.

talking about this area, in case its not clear.
[Imgur](https://i.imgur.com/zmSo6AF.png)

**Comment by glsorre** [comment]
Hello @eskoONE.

Amethyst is a tiling window manager that "lives" on top of the usual windows 10 shell. So I won't continue with this feature request.

I understand it but if you are looking for a more classic tiling window manger experience there are some good products out there. :)

Hope my thought is clear.

**Comment by eskoONE** [comment]
hey, no problem. would have been a nice feature to have, but not necessary. ty for taking your time to answer.
