### ISSUE TITLE
amethystwindows crashes when starting anki

### ISSUE THREAD

**Issue by eskoONE** [glsorre/amethystwindows#32]
**Describe the bug**
amethystwindows crashes the moment i start anki.

**To Reproduce**
just starting anki crashes the amethystwindows

**Expected behavior**
amethystwindows not crashing.

**Desktop (please complete the following information):**
 - OS: windows 10 home
 - Version 20h2

**Additional context**
its a qt app, which might be the reason why its crashing.

**Comment by glsorre** [comment]
@eskoONE This will be solved with #33

**Comment by glsorre** [comment]
@eskoONE Please check https://github.com/glsorre/amethystwindows/releases/tag/1.0.21147.1 and let me know.

**Comment by eskoONE** [comment]
seems to fix it at first glance but something is still making the program crash. i can reproduce it when i close all windows, open firefox, then anki and then opening windows terminal crashes it. i think it always crashes when doing it in this order and when none of the applications were tiled yet.

sometimes it also switches the master stack into slave when opening a new window to share the space with the slave stack, leaving the master stack empty. 

there is also sometimes a ghost window that is taking space when tiling. it happens randomly after crashing i think. it looks like this [https://i.imgur.com/s2o1u4A.png](https://i.imgur.com/s2o1u4A.png).

i can make a new bug report if you prefer to close this one to keep it tidy. i can also make a video with the problems im running into.

**Comment by glsorre** [comment]
This is super useful! Thank you. I will investigate and let you know.

**Comment by eskoONE** [comment]
i will try to provide whatever i can in a few hours. ill look into joining gitter as well. i dont know what that is rn. can you invite me to it or something?

**Comment by glsorre** [comment]
@eskoONE `1.0.21149.1` has solved many common crash reports as you confirmed in our Gitter chat. I am gonna close this. Thank you.
