### ISSUE TITLE
Crashes every so often

### ISSUE THREAD

**Issue by Explicit0xt** [glsorre/amethystwindows#35]
Hey, I really like this window manager but it crashes every time I open another window it seems It works for short periods and then crashes when opening a random window.

**Comment by glsorre** [comment]
Hello @Explicit0xt. Thanks for your feedback. I am happy you like it. I am working hard to fix some crash reports. Would you like to become a tester?

**Comment by Explicit0xt** [comment]
Sure I'd be down for testing :) so far the build 1.0.21149.1 you just released seems to be running stable I haven't seen it crash like it was doing before I'll notify you if I find any other bugs thanks for fixing this.

**Comment by glsorre** [comment]
Great this is good to hear. Would you mind join gitter or share a mail? I will share build previews there.

**Comment by Explicit0xt** [comment]
Yeah my email is fatalx@protonmail.ch
