### ISSUE TITLE
Key binds to switch to particular virtual desktops

### ISSUE THREAD

**Issue by calebkish** [glsorre/amethystwindows#37]
While Windows does already include hotkeys to switch to virtual desktops (`Ctrl+Win+Left` or `Ctrl+Win+Right`), it would be nice if we could map a key bind to switch to a particular virtual desktop. For example, to switch to virtual desktop 4, you could use a hotkey like `Alt+Shift+4` .

**Comment by glsorre** [comment]
Will do it.

**Comment by silver-dragon** [comment]
@calebkish 
Until the feature is added I recommend checking out [pmb6tz/windows-desktop-switcher](https://github.com/pmb6tz/windows-desktop-switcher) AutoHotkey script that adds this functionality.
