### ISSUE TITLE
App not loading on build 21390.1000

### ISSUE THREAD

**Issue by rmortes** [glsorre/amethystwindows#39]
**Describe the bug**
The app does nothing. I've tried every button and every key combo, and I can't get any response

**Screenshots**
![image](https://user-images.githubusercontent.com/56652057/122021352-e211c980-cdc5-11eb-9be5-f5ebf5dfd696.png)
I see nothing in this list, and I'm guessing there should be something

![image](https://user-images.githubusercontent.com/56652057/122021439-f5249980-cdc5-11eb-9aa3-196b7e735deb.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 21390.1000 (Dev)

**Comment by glsorre** [comment]
Hello @rmortes: most probably the systray component is crashed. In these cases you probably need a full relaunch. Could you please join [gitter](https://gitter.im/glsorre/amethystwindows?utm_source=share-link&utm_medium=link&utm_campaign=share-link) I think I can give better support there.

**Comment by glsorre** [comment]
Also I think I never tested that windows build.

**Comment by rmortes** [comment]
OS version bumped to 21390.1010 (Dev channel), the app is still not working

**Comment by rmortes** [comment]
Looks like the systray component is crashing every time I open the app. Are there any logs I can post?

**Comment by rmortes** [comment]
Quick update, still not working in 21390.2025

**Comment by tgolsson** [comment]
Added my WIP from yesterday for 21390 as a PR here: https://github.com/glsorre/amethystwindows/pull/44... Still a long way to go to demystifying the interfaces.

**Comment by rmortes** [comment]
Is there a way to beta test the PRs? I'd love to help you giving feedback with my system

**Comment by glsorre** [comment]
@rmortes unfortunately at the momnet no, builds are manually triggered; yearly minutes are quite limited. ☹️

**Comment by rmortes** [comment]
Sad to hear. Are local builds an option? I may not be used to Windows apps, but I'm quite tech savvy myself. As long as I don't require some Microsoft crap, like a developer account to build, I can try

**Comment by tgolsson** [comment]
@rmortes I think it'd work to use [Visual Studio Community](https://visualstudio.microsoft.com/vs/express/) to build it -- I'm using the Enterprise edition but the C# functionality should be the same as far as I know.

**Comment by belljames** [comment]
Do you have virtual desktops created?  
I've noticed the app crashes if I've removed the virtual destops.  Do win+tab and ensure you have  5 virtual desktops (or so).  This is a one-time setup.

**Comment by Sonsum** [comment]
I can confirm that I was having this issue and had no virtual desktops at the time. I was curious why I had 5 open sometime last week and closed them out. 

I made 5 desktops and the app started working again.

**Comment by glsorre** [comment]
This is actually strange because the app should check and eventually create the 5 vdesktops at launch. Sorry for delay but I am very busy I hope to be active again on Amethyst from the 14th to 21st of august.
