### ISSUE TITLE
Add ability to change location of "Main Window"

### ISSUE THREAD

**Issue by silver-dragon** [glsorre/amethystwindows#41]
What appears to be described as the "Main Window" in the documentation is locked over to the left-hand side. For my monitor setup, it works better to have the larger (Main) window over on the right-hand side. 

At the moment it doesn't appear that there is any way to change this, other than just switching to a different layout.

**Comment by glsorre** [comment]
Hello @silver-dragon. It is definitely a request I will follow on.

**Comment by ariccb** [comment]
This would be a great addition!
