### ISSUE TITLE
Doesn't see any windows on preview with WSL

### ISSUE THREAD

**Issue by janat08** [glsorre/amethystwindows#43]
**Describe the bug**
OS build 21390, Dev channel. I installed WSL, and now amethyst seems to be borked. It doesn't see any windows at all (the list of windows is empty). I imagine it requires WSL 2 getting installed, and then trying to run some linux gui app (which don't run either on my build.) I specifically launched ktorrent on ubuntu.

**Comment by janat08** [comment]
Feel free to close this. With the state of dev builds, its presumptuous to file bugs outside windows.

**Comment by janat08** [comment]
If you'd like to test that this works with WLS GUI apps, you don't have to get into dev build (I did so by accident). I couldn't be bothered to follow 6 steps consisting of copy and paste with the cmd.exe believe it or not, understanding the concepts of alpha and beta builds.

**Comment by glsorre** [comment]
Hello @janat08 we have problems with build 21390. Foll the issue #39.
