### ISSUE TITLE
RotateLayoutsCounterClockwise hotkey rotates layout twice

### ISSUE THREAD

**Issue by TwoLeaves** [glsorre/amethystwindows#45]
When hotkey 0x21 ("RotateLayoutsCounterClockwise") is activated via the default shortcut (shift+alt+win+space) the layout is rotated counterclockwise twice. Only one alert is shown.

It appears there are two if blocks targeting the same 0x21 hotkey in SystrayContext.cs. The first if statement rotates the layout and shows an alert while the second just rotates the layout. I imagine this is a mistake as it is the only hotkey defined twice.

I tried compiling branch june2021.1 with the second if statement removed. This appears to fix the problem. I made a pull request (separate to this issue sorry) with this change.

P.S. Thanks for making the only xmonad-style window manager I could find on Windows that uses Virtual Desktops rather than a custom implementation! I'm keeping an eye on "workspacer" also as it might be moving to a Virtual Desktops based implementation soon.

**Comment by TwoLeaves** [comment]
https://github.com/glsorre/amethystwindows/pull/46

**Comment by glsorre** [comment]
Double thanks @TwoLeaves. I will check your PR.

**Comment by glsorre** [comment]
Should be solved in https://github.com/glsorre/amethystwindows/releases/tag/2.0.0.1
