### ISSUE TITLE
mod1 + K swapped the window instead of moving the focus

### ISSUE THREAD

**Issue by feber** [glsorre/amethystwindows#47]
**Describe the bug**
Wrong executed command when shortcut file (`hotkeys.json`) is present. `mod1 + K` is expected to move the focus, instead it swapped the focused window.

**To Reproduce**
1. Copy [defaultHotkeys.json](https://github.com/glsorre/amethystwindows/blob/master/defaultHotkeys.json) into `%USERPROFILE%/AppData/Roaming/AmethystWindows/hotkeys.json`.
2. Start the application
3. Press `mod1 + K`
4. See the focused window swapped, instead of moving the focus.

**Expected behavior**
`mod1 + K` should move the focus, not swap the focused window.

**Screenshots**
**Case 1:** `%USERPROFILE%/AppData/Roaming/AmethystWindows/hotkeys.json` is not exist.
Initial state: 
![image](https://user-images.githubusercontent.com/1727318/127171113-4df253fb-8fc7-4ce3-bc35-c7c654ab0629.png)

After pressing `mod1 + K`: 
![image](https://user-images.githubusercontent.com/1727318/127171224-02c7ed26-30c3-4cc4-bf02-89c21bf1a3a8.png)

**Case 2:** `%USERPROFILE%/AppData/Roaming/AmethystWindows/hotkeys.json` exists, with the content copied from [defaultHotkeys.json](https://github.com/glsorre/amethystwindows/blob/master/defaultHotkeys.json).

Initial state: 
![image](https://user-images.githubusercontent.com/1727318/127171113-4df253fb-8fc7-4ce3-bc35-c7c654ab0629.png)

After pressing `mod1 + K`: 
![image](https://user-images.githubusercontent.com/1727318/127172471-5d35815b-2a48-41f1-9249-d86e469fd654.png)

Try to press `mod1 + K` again: 
![image](https://user-images.githubusercontent.com/1727318/127172634-a2a19b73-1fbb-4750-8a79-b6f9ab607120.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 build 19042
 - Version: 1.0.21149.1

**Additional context**
Digging through the code, I find the code does not align with the keyboard shortcut mentioned in the readme. [The code](https://github.com/glsorre/amethystwindows/blob/4bc49de/AmethystWindowsSystray/HooksHelper.cs#L160-L161) said `J` and `K` is designed for `SwapFocusedClockwise` and `ChangeFocusCounterclockwise`, respectively. In contrast, [the readme](https://github.com/glsorre/amethystwindows#keyboard-shortcuts) said `J` and `K` is to move the focuses around. Perhaps the code need to be fixed?

Swapping the `key` between `SwapFocusedClockwise` and `ChangeFocusClockwise` works, but I feel it is just a workaround.

Anyway, thanks for the awesome app! 👏

**Comment by glsorre** [comment]
@feber thank you! I will fix this.

**Comment by glsorre** [comment]
Should be solved in https://github.com/glsorre/amethystwindows/releases/tag/2.0.0.1
