### ISSUE TITLE
Feature request: Ability to maximize and restore a window

### ISSUE THREAD

**Issue by feber** [glsorre/amethystwindows#48]
**Is your feature request related to a problem? Please describe.**
When I have a bunch of windows in a screen and need to maximize one of them for a better view.

**Describe the solution you'd like**
Functionality for a window to be maximized (a window to take the whole screen) and restored (back to the previous state/layout before zoom). Additionally, bound the functionality to a shortcut (i.e. `mod1 + M`). Press once to maximize, press again to restore. Behaves like a toggle.

**Describe alternatives you've considered**
Probably have an option to activate monocle layout as a toggle. Toggle on monocle layout to simulate maximize, and toggle off to restore.

**Additional context**
The feature potentially a duplicate of [WinMaximize](https://www.autohotkey.com/docs/commands/WinMaximize.htm) and [WinRestore](https://www.autohotkey.com/docs/commands/WinRestore.htm) from AutoHotKey. I just found them out after creating this issue. If this feature is not necessary to be built into AmethystWindows, feel free to close the issue. Many thanks!

**Comment by belljames** [comment]
Hi feber,
on my system i use 2 options for this -

Click maximize/restore on the window itself.  (This works like a charm in amethystwindows whereas other tiling WMs i've tried will force the window back into the tiling mode.)

Use windows shortcut Win+up/down.  On my system I need to do this a few times to maximize (snap is turned on).

Hope that workaround helps for now

**Comment by feber** [comment]
Hi @belljames.
Thanks for the answer. I have no idea why I haven't try that before with AmethystWindows running.
Ah yes it works perfectly!

Guess I will close this issue then.
Again, thanks!
