### ISSUE TITLE
Incorrect actions mapped for "ChangeFocusClockwise" and "SwapFocusedClockwise"

### ISSUE THREAD

**Issue by tomvothecoder** [glsorre/amethystwindows#49]
**Describe the bug**
I was experimenting with this software and tried to match it with my MacOS Amethyst layout using a custom `hotkeys.json`. I noticed that the actions for `"ChangeFocusClockwise"` and `"SwapFocusClockwise"` should be swapped.

By default, when I tried using `"ChangeFocusClockwise"`, it would perform `"SwapFocuClockwise"` instead and vice versa.

**To Reproduce**
1. Add default `hotkeys.json`
2. Try each action
3. See that it isn't mapped correctly

**Expected behavior**
`"ChangeFocusClockwise"` should change focus, not swap.
`"SwapFocusClockwise"` should change swap, not focus.

**Additional Context**
My fixed `hotkeys.json` mapping (with additional keys to make my life easier).

```
    {
        "id": "ChangeFocusClockwise",
        "modifier": ["MOD_SHIFT", "MOD_ALT", "MOD_WIN"],
        "key": "0xBA",
        "actual_key": ";:",
        "comment": "This should be SwapFocusedClockWise"
    },
    {
        "id": "SwapFocusedCounterclockwise",
        "modifier": ["MOD_SHIFT", "MOD_ALT", "MOD_WIN"],
        "key": "0xDE",
        "actual_key": "single/double quote"
    },
    {
        "id": "SwapFocusedClockwise",
        "modifier": ["MOD_SHIFT", "MOD_ALT"],
        "key": "0xBA",
        "actual_key": ";:",
        "comment": "This should be ChangeFocusClockWise"
    },
    {
        "id": "ChangeFocusCounterclockwise",
        "modifier": ["MOD_SHIFT", "MOD_ALT"],
        "key": "0xDE",
        "actual_key": "single/double quote"
    },
```

**Comment by glsorre** [comment]
You're right. Will fix it.
