### ISSUE TITLE
Alacritty terminal doesn't get recognize in none decoration mode

### ISSUE THREAD

**Issue by reynerdev** [glsorre/amethystwindows#50]
In my terminal, alacritty when it's property decoration is none ( neither borders nor title bar) it doesn't get recognize by the app

This photo is when it's recognize ( borders and title bar are shown) 
![alacritty](https://user-images.githubusercontent.com/58928047/128578255-a9e9db1c-b662-4f98-a72d-4b551a2cacd6.png)

**Comment by glsorre** [comment]
@reynerdev thanks will give a look

**Comment by glsorre** [comment]
@reynerdev windows without decoration are filtered by default at the moment. This is to save some games (I am player of LoL, for example). I will add a selective adding of windows in v2. Here is a pre-release: https://github.com/glsorre/amethystwindows/releases/tag/2.0.0.1, let me know what you think.

**Comment by glsorre** [comment]
https://github.com/glsorre/amethystwindows/releases/tag/2.0.2.1 now has selective adding of windows
