### ISSUE TITLE
Place new windows in main pane

### ISSUE THREAD

**Issue by belljames** [glsorre/amethystwindows#52]
**Is your feature request related to a problem? Please describe.**
In tall layout new windows are placed bottom right (IE bottom of the stack area).  I'm always doing the hotkey to move them to the main area.

**Describe the solution you'd like**
In tall layout new windows are added to the main area, and last used window moves to top of the stack area.

**Describe alternatives you've considered**
So far just working around by opening window & hotkey-ing it into main area.

**Additional context**
![new_window](https://user-images.githubusercontent.com/57881574/128865179-a6b4a0d4-b89a-45f6-b7c3-f8974ef53546.gif)

**Comment by glsorre** [comment]
This has been implemented in https://github.com/glsorre/amethystwindows/releases/tag/2.0.2.1
