### ISSUE TITLE
Changing Mod1 and Mod2 default keys

### ISSUE THREAD

**Issue by juancarlis** [glsorre/amethystwindows#54]
Hi, is there a way to change the defualt mod keys or we should do it programmatically by forking the project? 

In the defaultHotkeys.json file the modifiers are called as "MOD_SHIFT", "MOD_ALT" or "MOD_WIN" and I can't the find where the definitions are. According to the Virtual-Key Codes I guess that the definitions should be: 
-  VK_SHIFT: 0x10
- VK_LWIN: 0x5B
- Alt Key: 0x12

Tks!

**Comment by glsorre** [comment]
It is now possible in v2 https://github.com/glsorre/amethystwindows/releases/tag/2.0.0.1
