### ISSUE TITLE
Vertical Layout is not positioning the windows correctly

### ISSUE THREAD

**Issue by JorgeBoscan** [glsorre/amethystwindows#55]
So at first I thought that vertical layout was using some other layout, but it seems that for portrait monitors it's miss calculating the position

Workaround for now: It seems that if I use a Window Padding > 7 it gets fixed if I have 2 windows opened, for 3 it would need to be > 8

Additional note: This monitor is a secondary monitor
![image](https://user-images.githubusercontent.com/1746127/130824090-15619ba0-08e4-4974-b976-ffcddac0c8b4.png)

**Comment by glsorre** [comment]
This should definitely be solved in https://github.com/glsorre/amethystwindows/releases/tag/2.0.0.1
