### ISSUE TITLE
Tall Shrinking and expanding main tile is too slow

### ISSUE THREAD

**Issue by JorgeBoscan** [glsorre/amethystwindows#56]
Shrinking/Expanding is way too slow compared to Amethyst on mac or workspacer on win10.
Also if we hit the command too fast multiple times, it won't poll them, it will wait for the last one before actually doing the change.

**Comment by glsorre** [comment]
Hello...I think the shrink expand command is debounced at the moment...I will see what I can do.

**Comment by glsorre** [comment]
https://github.com/glsorre/amethystwindows/releases/tag/2.0.0.1 should solve this
