### ISSUE TITLE
Multiple non-tiling apps

### ISSUE THREAD

**Issue by merriman-xyz** [glsorre/amethystwindows#57]
I have a few apps that don't tile: 
- Powershell 
- Webstorm/PyCharm 

Might be related to #28 

---

Much appreciate all the work you put into this. Makes a switch from Mac into Windows much more pleasant.

**Comment by rustemski** [comment]
There're Read only windows like Taskbar and Powershell, i must guess its related to your question

**Comment by sys9kdr** [comment]
cmd.exe also doesn't tiled.

**Comment by glsorre** [comment]
I think all privileged windows are not taken into consideration at the moment.

**Comment by glsorre** [comment]
Will close this in favor of #28
