### ISSUE TITLE
Doesn't detect applications in Windows 11

### ISSUE THREAD

**Issue by ClaudiaLapalme** [glsorre/amethystwindows#58]
**Describe the bug**
When you try to run the app in Windows 11, it doesn't detect applications and the UI is a little broken.

**To Reproduce**
1. Install the application 
2. Try to run it in Windows 11

**Expected behavior**
For the application to run as in Windows 10

**Screenshots**
Doesn't detect any of the 6 apps I have open
![image](https://user-images.githubusercontent.com/32103530/138100026-d97da700-8ae7-4690-8908-745ab1578f7c.png)

Once enabled, clicking again to disable does not work
![image](https://user-images.githubusercontent.com/32103530/138100157-ff52ce05-97dc-4df8-b5b9-ec8b1167c477.png)

Clicking on the three dots does not dynamically resize
![image](https://user-images.githubusercontent.com/32103530/138100293-381673af-8556-4f6a-8bfa-321677540cf1.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 Home, version 21H2, OS Build 22000.258
 - Browser Firefox
 - Version 93.0

**Additional context**
Filing this as a bug, but it might be better off as a feature request.

**Comment by glsorre** [comment]
Please @ClaudiaLapalme , try https://github.com/glsorre/amethystwindows/releases/tag/2.0.0.1 and let me know.
