### ISSUE TITLE
App Installer fails to install the program

### ISSUE THREAD

**Issue by nickduskey** [glsorre/amethystwindows#60]
**Describe the bug**
I am unable to install the program. I get the following error in App Installer:

```
App installation failed with error message: Appinstaller operation failed with error code 0x80D05011. Detail: Unknown error (0x80d05011)
```

**To Reproduce**
1. Go to https://amethystwindows.com/
2. Click on the "Install" button

**Expected behavior**
I expected the application to install

**Screenshots**
![image](https://user-images.githubusercontent.com/8136235/141111832-1b5fe6fc-d4cc-431b-8b08-d9a040ccef26.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Browser: Chrome v95.0.4638.69
 - Version 21H1
 - OS Build 19043.1348
 - Experience Windows Feature Experience Pack 120.2212.3920.0

**Additional context**

**Comment by rustemski** [comment]
MicrosoftStore version? or Github version? 
Due to some bundle version i guess

**Comment by nickduskey** [comment]
I just clicked Install from the website (https://amethystwindows.com/) and clicked install. I'm assuming that is using the MS app installer. As far as github version I'm not sure what you mean by that.  For Microsoft Store version here is the version I am running:

![image](https://user-images.githubusercontent.com/8136235/141369078-7b2223fc-e828-4f83-a53c-d571a5671e30.png)

Version 12107.1001.15.0

**Comment by glsorre** [comment]
I have no clue...I will try to replicate it.

**Comment by SomePersonOfficial** [comment]
I was having the same issue, to fix I updated app installer from the microsoft store and it worked.

**Comment by holodrum** [comment]
I'm on the newest version of the app installer (and Windows 10) and I'm getting a somewhat related error as well, though, in my case, I notice that it also states that it's an "Untrusted App" and the publisher is "Unknown", which is weird, as that wasn't the case in the past.

I've tried multiple releases, all give the same error, including the ones I've used in the past without any issues.

![ApplicationFrameHost_mC4foI0tD7](https://user-images.githubusercontent.com/17521390/147856764-d5784f92-10e9-43b2-bd09-45aaaf72e5d4.png)

If I try to install directly from the website, I get a different message.

![ApplicationFrameHost_XzRC8ZpQdd](https://user-images.githubusercontent.com/17521390/147856415-60374542-b35b-4ea6-96fb-7f9339a74a71.png)

**Comment by holodrum** [comment]
I'm on the newest version of the app installer (and Windows 10) and I'm getting a somewhat related error as well, though, in my case, I notice that on the newest version of the App Installer, it also states that it's an "Untrusted App" and the publisher is "Unknown", while on earlier versions of the App Installer, the publisher is correct (Giuseppe Sorrentino) while it's still untrusted.

I've tried multiple releases, all give the same error, including the ones I've used in the past without any issues.

![ApplicationFrameHost_mC4foI0tD7](https://user-images.githubusercontent.com/17521390/147856764-d5784f92-10e9-43b2-bd09-45aaaf72e5d4.png)

If I try to install directly from the website, I get a different message.

![ApplicationFrameHost_XzRC8ZpQdd](https://user-images.githubusercontent.com/17521390/147856415-60374542-b35b-4ea6-96fb-7f9339a74a71.png)

**Comment by glsorre** [comment]
hello @holodrum the ssl certificate is expired on the 31st. I renewed it but I need to do a build. Hope to do it tomorrow.

Sorry about that.

**Comment by holodrum** [comment]
@glsorre No worries, thanks for the info, looking forward to being able to use this again :)

btw, is it just me misremembering, or wasn't Amethyst in the windows package manager repository/store (whatever Microsoft calls it at this point)? I feel like I used to be able to install this with winget earlier in 2021?

**Comment by Kryptos-123** [comment]
Were you able to do the build ?

**Comment by glsorre** [comment]
Hello @Kryptos-123, not yet. I will keep you posted.

**Comment by NylonDiamond** [comment]
Still not ssl cert? I'd love to try it out!

**Comment by Galileji** [comment]
Probably issue #63 could be merged with this issue (I'm new to github, I don't know if I can do it myself)

**Comment by glsorre** [comment]
Please follow #64. I won't update this.
