### ISSUE TITLE
Remove/add layouts that are cycled through

### ISSUE THREAD

**Issue by Menn1s** [glsorre/amethystwindows#61]
As with the original Amethyst, it would be nice to remove layouts that aren't often used so that the user doesn't have to cycle through all of the layouts.

**Comment by AndreasNasman** [comment]
This is a missing feature that would be really nice to have!
I've used the Mac version of Amethys extensively and only find myself using the Fullscreen and Wide layouts. Cycling through all the layouts feels a bit clunky.

**Comment by micoro** [comment]
A potentially easy solution could be to be able to set hotkeys for each possible layout.
This way it's possible to select the desired layout without cycling all of them. 
I guess most people like me just use 2 layout: monocle and their favorite version of tiled layout.

**Comment by glsorre** [comment]
It will come. Hope to have a bit of time to spend on Amethyst in September.
