### ISSUE TITLE
App Installer refuses to install: "This app package is not signed with a trusted certificate."

### ISSUE THREAD

**Issue by S31Syntax** [glsorre/amethystwindows#64]
When launching either APPINSTALLER or APPXBUNDLE file, the App Installer halts immediately and states that the app is not signed with a trusted certificate. Specifically
`This app package is not signed with a trusted certificate. Contact your system administrator or the app developer to obtain a new certificate or app package with trusted certificates. The root certificate and all immediate certificates of the signature in the app package must be trusted (0x800B010A)`

**To Reproduce**
1. Download either APPINSTALLER or APPXBUNDLE file
2. Launch either file
3. "Install" button is greyed out, error is displayed

**Expected behavior**
Install button should be active and app should install

Manually installing the certs in the package did not resolve the issue, claims that the certificates are either expired or invalid.

![image](https://user-images.githubusercontent.com/58040398/148975727-ee008416-77bc-481b-bedb-b7bc4a3968d1.png)

**Comment by andre68723** [comment]
Certificate expired on 1/1/2022.

**Comment by glsorre** [comment]
Yeah I know. I even renewed it but haven't found time to run a build. 🤦 
Hope to do that soon.
Sorry.

**Comment by mlea13** [comment]
Any update on this? I'd also love to install it, but I'm blocked by the certificate issue.

**Comment by micheldenario** [comment]
Same problem here, any update?

**Comment by mathesonphillip** [comment]
Also eagerly waiting

**Comment by glsorre** [comment]
Hi all! Sorry for the long absence. I just requested the cert. As soon as it is released I will run a build.

![certifcateIssue](https://user-images.githubusercontent.com/4059141/152677038-81cdf06a-09d0-41e7-bafe-6ad61d1fefe8.png)

**Comment by Liam-Wirth** [comment]
awesome! I was worried that this was starting to take the course of most passion projects (mine included) happy to see you're still working on it!

**Comment by glsorre** [comment]
Hello, the certificate issuing is taking longer than expected. Sorry about that.

@Liam-Wirth believe me I would like to work at amethyst much more than what I can do

**Comment by glsorre** [comment]
Hi all!

Unfortunately Sectigo has refused to release me a code signing certificate. I recently changed residency and it seems my not updated passport is not good to obtain the certificate.

I have another opportunity to get it which is to have a face to face authentication with a notary but is too expensive for me and renewing my document is too slow.

Anyone can help here with any suggestion on a reliable Code Signing supplier which is not supercosty and is not certum.eu?

**Comment by pex81** [comment]
> Hi all!
> 
> Unfortunately Sectigo has refused to release me a code signing certificate. I recently changed residency and it seems my not updated passport is not good to obtain the certificate.
> 
> I have another opportunity to get it which is to have a face to face authentication with a notary but is too expensive for me and renewing my document is too slow.
> 
> Anyone can help here with any suggestion on a reliable Code Signing supplier which is not supercosty and is not certum.eu?

But [Let's Encrypt](https://letsencrypt.org) ?

**Comment by mcampbell** [comment]
Is there something special about this software that requires signing?

**Comment by glsorre** [comment]
@mcampbell nope any win 10 software needs code signing

**Comment by choskeli** [comment]
For anyone looking for a temporary fix, I built from master and generated a self signed cert.

[Download Package](https://icedrive.net/s/V1y24FWDAjvzwPwhXQX4ZFRR87if) 
[Download Cert](https://icedrive.net/s/WN2RFwbAg5XtkRvz3GBw2CQjvA8w)

You can trust the cert with: `certutil.exe -addstore TrustedPeople AmethystWindowsPackaging_1.0.1.0_x86_x64_arm.cer`

May also solve #65

**Comment by glsorre** [comment]
@choskeli thanks for helping.

I have 2 good news: 
- Amethyst windows has been elected for a free open-source certificate from singpath (which I really would like to thank you). So I wiil be able to update site and packages soon;
- a new version partially rewritten is available in the `wpf` branch. Expect this to be pre-released in the next days.

**Comment by apfsx** [comment]
> For anyone looking for a temporary fix, I built from master and generated a self signed cert.
> 
> 
> 
> [Download Package](https://icedrive.net/s/V1y24FWDAjvzwPwhXQX4ZFRR87if) 
> 
> [Download Cert](https://icedrive.net/s/WN2RFwbAg5XtkRvz3GBw2CQjvA8w)
> 
> 
> 
> You can trust the cert with: `certutil.exe -addstore TrustedPeople AmethystWindowsPackaging_1.0.1.0_x86_x64_arm.cer`
> 
> 
> 
> May also solve #65

Hello! Thank you! Do you have instructions on how I can also build quickly? Either local or through azure if it's faster? Much appreciated.

**Comment by glsorre** [comment]
Hello https://github.com/glsorre/amethystwindows/releases/tag/2.0.0.1! Enjoy,
