### ISSUE TITLE
Cannot Install App, error 0x800B0101

### ISSUE THREAD

**Issue by rodrigojuliaodsgn** [glsorre/amethystwindows#65]
When trying to install from .appinstaller I receive the following error:
App installation failed with error message: error 0x800B0101: Opening the package from location AmethystWindowsPackaging_1.0.21149.1_x86_x64_ARM.appxbundle failed. (0x800b0101).

Aware of the other thread regarding being unable to install but the error given as justification differs from the one I get.
Was really looking forward to trying out your application, hope it gets resolved soon

**Comment by GildartsClive** [comment]
see issue #64

**Comment by glsorre** [comment]
I think and hope is always releated to the cert.

**Comment by apfsx** [comment]
> I think and hope is always releated to the cert.

I still cannot install the application due to the same certificate error. In the meantime while this is getting fixed, is there a way to force installation? I enabled developer mode in my settings but still wouldn't let me install.
