### ISSUE TITLE
Ability to hide title bars via settings and hotkeys

### ISSUE THREAD

**Issue by choskeli** [glsorre/amethystwindows#66]
**Is your feature request related to a problem? Please describe.**
Title bars (top of each window) take up extra space and aren't useful in many (but not all) applications. When you have several applications on the screen this wasted space adds up.

**Describe the solution you'd like**
Give the ability to disable title bars by default. Add list of exe's that _should_ have title bars to settings config file (e.g. Chrome since tabs are on the title bar). Probably also have a hotkey to toggle it on the fly.

**Describe alternatives you've considered**
I tried to use bug.n (which does have this feature) but it should be called bug.e

**Comment by glsorre** [comment]
@choskeli I sincerely think Amethyst is not a "classic" tiling window manager but is born to live within the borders of windows so I won't proceed with this feature

have you had the opportunity to test v2? I am interested in your feedback
