### ISSUE TITLE
Steam is not sized properly and can crash Amethyst when minimized to taskbar and re-opened

### ISSUE THREAD

**Issue by choskeli** [glsorre/amethystwindows#70]
**Describe the bug**
Steam is not sized properly and can crash Amethyst. This may happen with other applications that minimize to the taskbar when closed and re-opened.

**To Reproduce**
1. Open steam
2. Open edge or chrome (Steam will now be the wrong size)
3. Hit the 'X' for steam (so it goes to taskbar)
4. Open steam again (Amethyst will now crash)

**Comment by Stobz0** [comment]
I am not seeing the crash portion of this. However, I am noticing that the main Steam window is not resizing as expected. 
Reproduce:
1. Open Steam
2. Open 2 Notepads
3. Click on non main window, and press Alt+Shift+Enter to make it the main window
4. The Steam window does not normally resize and move to it's proper location unless it is being promoted to main window

**Comment by glsorre** [comment]
Thanks @Stobz0. I am looking into it.
