### ISSUE TITLE
Discord crashes amethyst

### ISSUE THREAD

**Issue by choskeli** [glsorre/amethystwindows#71]
**Describe the bug**
Launching discord crashes amethyst

**To Reproduce**
1. Exit discord (if it started with windows)
2. Launch two applications on 2nd monitor
3. Launch discord on 2nd monitor (Amethyst crashes and discord doesn't resize properly)

**Comment by choskeli** [comment]
Also wanted to add that #66 #67 #68 #69 #70 and #71 were tested with master branch built from source

**Comment by apfsx** [comment]
> Also wanted to add that #67 #68 #69 #70 and #71 were tested with master branch built from source

I'm also experiencing the same issues in all these you listed. Crashes very often when minimizing and maximizing windows from taskbar. I also have dual monitors connected.

**Comment by glsorre** [comment]
Hi @choskeli  @apfsx I am not able to replicate none of the problems you report. Discord seems to be manage properly on my system.
