### ISSUE TITLE
Not compatible with latest App Installer

### ISSUE THREAD

**Issue by bardo84** [glsorre/amethystwindows#72]
Not compatible with latest App Installer
- please contact developer to update code..
Thx

**Comment by angelogiuseppe** [comment]
I get this screen, but the install button is not enabled, this is running the downloaded file: 

![image](https://user-images.githubusercontent.com/10346249/154762968-3820587a-6c85-468e-9e09-fec7ed4b65dc.png)

When clicking on the install button of the website I get this: 

![image](https://user-images.githubusercontent.com/10346249/154763048-a361f0bb-7a9d-4159-b444-01fba68cf47a.png)

I am currently on Windows 11 stable branch

**Comment by glsorre** [comment]
Hello check #64. This is known and I am trying to ship a solution.
