### ISSUE TITLE
Add "About" tab

### ISSUE THREAD

**Issue by slel** [glsorre/amethystwindows#73]
It would be nice if the Amethyst pane had an "About" tab
with the current version and an option to check for updates.

The alternative is of course to visit the releases page at

    https://github.com/glsorre/amethystwindows/releases

and decide whether to update.

**Comment by glsorre** [comment]
@slel definitely a good idea

**Comment by Stobz0** [comment]
I just found AmethystWindows while researching similar solutions. I think an about tab would be useful too. The version and update option would be useful. However, in my case I was looking for the about tab to hopefully find out about the licensing information and/or link to the websites.
