### ISSUE TITLE
Not Tiling Some Applications

### ISSUE THREAD

**Issue by Stobz** [glsorre/amethystwindows#76]
Continued from Closed Issue #75 

The Ecosystem game window does not display in any of the Amethyst tabs including Managed Windows/Excluded Windows/Filters/Additions, so I cannot try to select or add it.
After investigating the Amethyst code more, it looks like game window might not be listed at all because for Ecosystem
`desktopWindow.AppName == ""`

I think I've narrowed it down to this.
In DesktopWindow.cs, function GetAppName(), line 208

```
if (name == null)
	{
		name = fileName.Split(new string[] { "\\" }, StringSplitOptions.None).Last();
	}
	AppName = name;
```

When comparing `if (name == null)`, it never processes the final name assignment option and the function would end with
`AppName == ""`
I changed it to `if (name == "")`
Now Ecosystem and other apps that fail the initial naming options should display in the list.
It now displays Ecosystem.exe as a UnityWndClass under the Excluded Windows tab, and I can select it from there and use the Add App button. This allows the game to function normally and have Amethyst control it.

**Comment by glsorre** [comment]
this has been merged on 2.0.196.1...tnx
