### ISSUE TITLE
Fesh Install Packaging certificate errors (1.0.21149.1 Latest Stable)

### ISSUE THREAD

**Issue by jimmy6DOF** [glsorre/amethystwindows#79]
Below is the error statement and not possible to complete the install so users must go to MSI's in Alpha release (Win10 PRO 21H2):

ERROR:
This app package is not signed with a trusted certificate. Contact your system administrator or the app developer to obtain a new certificate or app package with trusted certificates. The root certificate and all immediate certificates of the signature in the app package must be trusted (0x800B010A)

**Comment by glsorre** [comment]
hello @jimmy6DOF, I do not suopport v1 anymore. sorry.
