### ISSUE TITLE
Frequent crashes after changing Hotkeys

### ISSUE THREAD

**Issue by max-sixty** [glsorre/amethystwindows#81]
The app looks great at first glance!

But I'm trying to set the shortcuts to something similar to what I use on Mac, and struggling:
- I'm trying to set `c-a-p` & `c-a-n` to "Swap Focus Counterclockwise / Clockwise"
- I'm trying to set `c-a-j` & `c-a-k` to "Move Focus Previous / Next Screen" 

But after changing these settings:
- "Swap Focus Counterclockwise / Clockwise" works well
- "Move Focus Previous / Next Screen" doesn't work, and Amethyst crashes after a few tries

I eventually need to manually delete the Settings file, since the app crashes enough for it to be difficult to restore.

---

FWIW when I don't change the settings, `c-a-n` for "Next Screen" doesn't work.

I'm using the latest [2.0.4.1 Alpha](https://github.com/glsorre/amethystwindows/releases/tag/2.0.4.1)

**Comment by glsorre** [comment]
Hello @max-sixty,

thank you for notifying. I will give a look. I spent very few hours on amethyst recently but I hope to recover. There are a lot of possible reasons for the behavior you report.

I will let you know.

**Comment by haru02w** [comment]
That's the only program I fell comfortable using after being on DWM for years.
Unfortunately, I'm having this same issue.
Hope that it'll be fixed soon. Thanks

**Comment by glsorre** [comment]
this should be solved on 2.0.196.1

**Comment by max-sixty** [comment]
This seems to be fixed! Thank you.

I have another large issue, I'll open a new issue
