### ISSUE TITLE
Be able to use Win key in creating new hotkey combos

### ISSUE THREAD

**Issue by ariccb** [glsorre/amethystwindows#89]
I have a programmable keyboard that has Win+Ctrl+Alt set to one key, and Win+Shift+Ctrl+Alt as another key (Hyper key), and I'm not able to use them to set new hotkeys in the settings window. When I use it to create the shortcut, the Win key is omitted for some reason. 

This would help me not need to contort my fingers so much to hit all Shift+Win+Alt at the same time everytime I use a hot key

**Comment by max-sixty** [comment]
FWIW I have a similar experience — if I try setting a shortcut like `Shift+Alt+Win+K`, it appears as `Shift+Alt+K`.

I can _use_ existing shortcuts that include the Win key; it only seems to not work when setting the shortcuts
