### ISSUE TITLE
AmethystWindows not working after Windows 22H2 update

### ISSUE THREAD

**Issue by gvalenzuelarg** [glsorre/amethystwindows#93]
Source
AmethystWindows

Summary
Stopped working

Date
‎27/‎01/‎2023 14:09

Status
Report sent

Description
Faulting Application Path:	C:\Program Files\WindowsApps\f04c436a-4cda-455d-b409-4520a608c6d0_2.0.222.1_neutral__wbnnev551gwxy\AmethystWindows\AmethystWindows.exe

Problem signature
Problem Event Name:	MoAppCrash
Package Full Name:	f04c436a-4cda-455d-b409-4520a608c6d0_2.0.222.1_neutral__wbnnev551gwxy
Application Name:	praid:App
Application Version:	1.0.0.0
Application Timestamp:	6355849f
Fault Module Name:	KERNELBASE.dll
Fault Module Version:	10.0.22621.1105
Fault Module Timestamp:	c16aac06
Exception Code:	e0434352
Exception Offset:	00147452
OS Version:	10.0.22621.2.0.0.768.101
Locale ID:	3072
Additional Information 1:	2beb
Additional Information 2:	2beba6fb4680d73a8c78ca7c24ccdb46
Additional Information 3:	3636
Additional Information 4:	363600d01b0027a84ddf27d112eb0d6d

Extra information about the problem
Bucket ID:	8f0cbb5cb4834283d13da41b9d30293e (1242329510732376382)

**Comment by glsorre** [comment]
Please move to v2

**Comment by gvalenzuelarg** [comment]
Thank you for the quick reply! This happened with v 2.0.222.1. I also tried other v2 subversions with the same result.

**Comment by xmika** [comment]
Same here, I tried installing v2.0.222.1 on 22H2 (22621.1194) and upon launch it tiles windows but none of the keyboard shortcuts work. Manually trying to change them makes no difference.

**Comment by daveksd** [comment]
Same issue as @xmika over her on 22H2 as well.  Crashes every few minutes and only one keyboard shortcut works (mod1 + space).
